alias en='su'
alias sho='cat'
alias inc='grep'
alias sl='ls'
alias trains='/usr/bin/sl'
alias grep='grep --colour=auto'
alias du='pwd; /usr/bin/du -ch 2>/dev/null | grep total'
alias ifc='/sbin/ifconfig'
alias v='vim'
alias p='/usr/bin/perl'
alias cls='clear'
alias gpl='git pull'
alias gps='git push'
alias gc='git commit -am'
alias ga='git add .'
alias gb='git branch'
alias gs='git status'
alias rm='rm -rf'
#alias rel='source ~/.bashrc'
alias fuck='pkill -9 -f'
alias fucking='sudo'
alias ':w'='echo "Need to open vim first..."'
alias ':q'='echo "Need to open vim first..."'
alias idlookup='python /home/cohoeg/Projects/pub/scripts/ldap/idlookup.py'
alias ls='/bin/ls --color=tty -lh'
alias dynamo='java -Djava.library.path=~/Software/DynamoDBLocal/DynamoDBLocal_lib -jar ~/Software/DynamoDBLocal/DynamoDBLocal.jar -sharedDb -dbPath ~/Software/DynamoDBLocal'
alias d='docker'
alias tmux='tmux -2'
