alias en='su'
alias sho='cat'
alias inc='grep'
alias sl='ls'
alias trains='/usr/bin/sl'
alias grep='grep --colour=auto'
alias ifc='/sbin/ifconfig'
alias v='vim'
alias p='/usr/bin/perl'
alias cls='clear'
alias gpl='git pull'
alias gps='git push'
alias gc='git commit -am'
alias ga='git add .'
alias gb='git branch'
alias gs='git status'
alias rm='rm -rf'
#alias rel='source ~/.bashrc'
alias fuck='pkill -9 -f'
alias fucking='sudo'
alias ':w'='echo "Need to open vim first..."'
alias ':q'='echo "Need to open vim first..."'
alias ls='/bin/ls --color=tty -lh'
alias ls='/bin/ls --color=tty -lh'
alias dynamo='java -Djava.library.path=~/Software/DynamoDBLocal/DynamoDBLocal_lib -jar ~/Software/DynamoDBLocal/DynamoDBLocal.jar -sharedDb -dbPath ~/Software/DynamoDBLocal'
alias d='docker'
alias dc='docker-compose'
alias tmux='tmux -2'
alias nssdig='getent hosts'
alias dbus-reset='dbus-send --print-reply --dest=org.xfce.Panel /org/xfce/Panel org.xfce.Panel.Terminate boolean:true'
