#!/bin/bash

set -e

# Copyright 2017 Grant Cohoe (grant@grantcohoe.com)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Set some local stuff
VBOXMANAGE=$(which vboxmanage)
TMP_DIR=$(mktemp -d)

# Set some remote stuff
VBOX_REPO_HOST="http://download.virtualbox.org"
VBOX_EXTPACK_PREFIX="Oracle_VM_VirtualBox_Extension_Pack-"
VBOX_EXTPACK_SUFFIX=".vbox-extpack"

# This is needed to ensure the kernel modules are loaded prior to installing
# the extpack.
sudo vboxconfig

# Figure out which version of vbox we are working with
raw_version=$($VBOXMANAGE -v)
version=$(echo "${raw_version}" | cut -d 'r' -f 1)
release=$(echo "${raw_version}" | cut -d 'r' -f 2)

# Build the filename and path of the extension pack
extpack_filename="${VBOX_EXTPACK_PREFIX}${version}-${release}${VBOX_EXTPACK_SUFFIX}"
extpack_path="${VBOX_REPO_HOST}/virtualbox/${version}/${extpack_filename}"

# Download the extpack
wget --quiet -O "${TMP_DIR}/${extpack_filename}" "${extpack_path}"

# Install

# In 5.1.20, vbox added a license parameter to the installer. This appears to
# be a SHA256 hash of the license file in the extpack gzip archive. It is
# unknown if the value is going to change as time goes on, so we must deal
# with it. Oracle are a bunch of dicks, even AM said so.
#
# https://github.com/caskroom/homebrew-cask/issues/32560
license_key=$(zgrep -a "SHA256 (ExtPack-license.txt) = " "${TMP_DIR}/${extpack_filename}" | cut -d '=' -f 2 | sed 's/ //g')

# Actually install the package
sudo ${VBOXMANAGE} extpack install --replace "${TMP_DIR}/${extpack_filename}" --accept-license="${license_key}"

# Done!
echo "Done"
